name: CD
on:
  workflow_dispatch: 
  push:
    branches: main
    paths:
      - 'src/**' # Deploy web every change in src folder
      - '.github/workflows/cd.yml'
    
permissions:
  contents: read

jobs:
  build-itchio:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.1

      - name: Cache build/zig-cache
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.zig-cache
          key: .zig-cache
          restore-keys: .zig-cache

      - name: Setup Environment
        run: | 
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends python3 libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev cmake wget
          wget --no-verbose https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz
          mkdir -p zig-folder
          tar xf zig-x86_64-linux-0.15.1.tar.xz -C ./zig-folder  --strip-components=1
          rm ./zig-x86_64-linux-0.15.1.tar.xz
          chmod +x ./zig-folder/zig
        shell: bash
     
      - name: Build Web Project
        id: buildWeb
        run: |
          ./zig-folder/zig build -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall -fno-incremental
          